### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by EliseMre** [Lywel/Audeo#3]
Ca serait bien de pouvoir corriger le détail que je t'ai envoyé tout à l'heure, lorsqu'on doit augmenter ou diminuer les notes, tu vois ?

**Comment by Lywel** [comment]
Pour la suppression des flèches dans les zone d'entrée des notes, il faut faire un compromis.
En effet, en attendant de trouver une solution complète il faut choisir entre : 
 * La séléction automatique du clavier numérique sur les mobiles, mais des fleches seront visible sur les ordinateurs *(Réglage acutel)*
 * La suppression des fleches sur tous les navigateurs mais le clavier par default sur les mobiles sera alphabetique.

**Comment by Lywel** [comment]
Une solution complète à été trouvée finalement
