### ISSUE TITLE
Rajouter des points

### ISSUE THREAD

**Issue by EliseMre** [Lywel/Audeo#6]
Ca serait mieux de rajouter des points "." à la fin de chaque phrases.
Genre "calcul de vos moyennes auX concours BCE." (avec un point et un X à "aux")
et pareil à la fin "les écoles qui vous seront accessibles."

**Comment by Lywel** [comment]
Je ne suis pas sur que metre des points à la fin d'un titre soit une bonne chose. Pour le reste ça sera fait.
