### ISSUE TITLE
Reformuler la phrase d'intro

### ISSUE THREAD

**Issue by EliseMre** [Lywel/Audeo#8]
Il faut reformuler parce que la phrase commence par "calcul (...) vos écoles" mais on calcule pas une école on calcule une moyenne !

Je pense que ca serait mieux de marquer :
"Audeo calcule votre moyenne en fonction de vos prévisons, et vous informe des écoles accessibles."

**Comment by EliseMre** [comment]
Informe j'aime pas trop mais un autre mot du même genre. Je cherche.

**Comment by Lywel** [comment]
"Audeo calcule votre moyenne en fonction de vos prévisons. Vous saurez alors facilement quelles écoles vous sont accessible." ?
